### ISSUE TITLE
documentaion

### ISSUE THREAD

**Issue by samim23** [vivanov879/draw#1]
hey there. Could you give some pointers on usage of library and how to feed it your own data? got it running but slightly confusing so far. thanks!

**Comment by vivanov879** [comment]
thanks for checking out the project -- updated the readme

**Comment by vivanov879** [comment]
did you manage to run the script ? it runs several minutes and gives some visible result

**Comment by samim23** [comment]
have not had the time so far, blame deepdream. Will get to this soon i hope!

**Comment by vivanov879** [comment]
ok -- thanks for looking at it -- if you have any suggestions, ill improve on it. deepdream is fascinating

**Comment by samim23** [comment]
If you find a way to apply draw to custom data sets (e.g. images of any kind), we might have something more interesting than deepdream on our hands. lets explore ;-)

**Comment by vivanov879** [comment]
indeed -- ill try it out next weekend

**Comment by samim23** [comment]
ok great, informed me if you do, i´ll do an experiment with it

**Comment by vivanov879** [comment]
sure
